name: anime_twist
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  momentum: ^1.2.7
  shared_preferences: ^0.5.8
  equatable: ^1.2.0
  relative_scale: ^1.0.8
  http: ^0.12.1
  cached_network_image: ^2.2.0+1
  encrypt: ^4.0.2
  tuple: ^1.0.3
  device_preview: ^0.4.7
  edit_distance: ^0.4.1
  video_player_header: ^0.10.2+4
  yaml: ^2.2.1


  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.1.0



flutter:

  uses-material-design: true
  assets:
    - assets/images/
